version: "3.7"

services:
  app:
    build:
      context: ./app
      args:
        TZ: ${TZ}
    volumes:
      - example_app_vendor:/app/vendor
      - ./../app:/app
    working_dir: /app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - example_app_mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  nginx:
    image: nginx:1.19-alpine
    depends_on:
      - app
    ports:
      - 3000:80
    volumes:
      - ./../app:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: ${TZ}

volumes:
  example_app_vendor:
  example_app_mysql_data:
